### ISSUE TITLE
코드 수정 요청 사항.

### ISSUE THREAD

**Issue by snoopspy** [truculentas/add-nbo#1]
https://github.com/truculentas/add-nbo/commit/9b192dc290b7255ed6c9ba7c5fe994fff5c42f87#r120052670

https://github.com/truculentas/add-nbo/commit/9b192dc290b7255ed6c9ba7c5fe994fff5c42f87#r120052717

https://github.com/truculentas/add-nbo/commit/9b192dc290b7255ed6c9ba7c5fe994fff5c42f87#r120052807

**Comment by truculentas** [comment]
피드백 확인했습니다. 감사합니다!

**Comment by JeonSH-Francesco** [comment]
https://github.com/truculentas/add-nbo/blame/3da38b7573f4ae63af943a00b8a769306edb8754/ntoh_read.c#L12
